[package]
description = "Nintendo 3DS Discord"
name = "rust3ds-discord"
version = "0.0.1"

[dependencies]
ctru-rs = { path = "../ctru-rs/ctru-rs" }
ctru-sys = { path = "../ctru-rs/ctru-sys" }

[profile.dev]
lto = true

[profile.release]
lto = true
